//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IATec.Shared.HttpClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IATec.Shared.HttpClient.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Bad Request.".
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Circuit breaker half-open.".
        /// </summary>
        public static string CircuitBreakerHalfOpen {
            get {
                return ResourceManager.GetString("CircuitBreakerHalfOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Circuit breaker opened for {0} seconds.".
        /// </summary>
        public static string CircuitBreakerOpenedForSeconds {
            get {
                return ResourceManager.GetString("CircuitBreakerOpenedForSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Circuit breaker open. Please try again later.".
        /// </summary>
        public static string CircuitBreakerOpenTryAgainLater {
            get {
                return ResourceManager.GetString("CircuitBreakerOpenTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Circuit breaker reset.".
        /// </summary>
        public static string CircuitBreakerReset {
            get {
                return ResourceManager.GetString("CircuitBreakerReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Deserialization error.".
        /// </summary>
        public static string DeserializationError {
            get {
                return ResourceManager.GetString("DeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Forbidden.".
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Internal Server Error.".
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Not Found.".
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Request error.".
        /// </summary>
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Retry attempt {0} after {1} sec.".
        /// </summary>
        public static string RetryAttemptMessage {
            get {
                return ResourceManager.GetString("RetryAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Request timed out.".
        /// </summary>
        public static string TimeoutMessage {
            get {
                return ResourceManager.GetString("TimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Unauthorized.".
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
