//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IATec.Shared.HttpClient.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IATec.Shared.HttpClient.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CircuitBreakerHalfOpen {
            get {
                return ResourceManager.GetString("CircuitBreakerHalfOpen", resourceCulture);
            }
        }
        
        public static string CircuitBreakerOpenedForSeconds {
            get {
                return ResourceManager.GetString("CircuitBreakerOpenedForSeconds", resourceCulture);
            }
        }
        
        public static string CircuitBreakerOpenTryAgainLater {
            get {
                return ResourceManager.GetString("CircuitBreakerOpenTryAgainLater", resourceCulture);
            }
        }
        
        public static string CircuitBreakerReset {
            get {
                return ResourceManager.GetString("CircuitBreakerReset", resourceCulture);
            }
        }
        
        public static string DeserializationError {
            get {
                return ResourceManager.GetString("DeserializationError", resourceCulture);
            }
        }
        
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        public static string RetryAttemptMessage {
            get {
                return ResourceManager.GetString("RetryAttemptMessage", resourceCulture);
            }
        }
    }
}
