trigger:
  branches:
    include:
      - main

pr: none

pool:
  name: IATec-Builds-Agents

variables:
  buildConfiguration: 'Release'

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $version = [xml](Get-Content  src/IATec.Shared.HttpClient.csproj)
        $packageVersion = $version.Project.PropertyGroup.Version
        Write-Host "##vso[task.setvariable variable=packageVersion]$packageVersion"
    displayName: 'Get project version'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Dotnet build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/IATec.Shared.HttpClient.csproj' 
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      nobuild: true 
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'packageVersion'
    displayName: 'Pack NuGet package with dotnet pack'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet authenticate'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: 'IATec.Community'
      allowPackageConflicts: true